### PR TITLE
Add tests for Label Component

### PR DESCRIPTION
**Pull request by ClarkeCDC**
I have added tests for Label Component. I was going to use Snapshots but found the BaseLabel was causing issues. Done it a slightly different way with .html().

### CODE REVIEW

**Comment by ClarkeCDC** [comment]
I have added tests for Label Component. I was going to use Snapshots but found the BaseLabel was causing issues. Done it a slightly different way with `.html()`.

**Review by kevinkuszyk — APPROVED** [review]

**Comment by kevinkuszyk** [comment]
@ClarkeCDC thanks for the contribution.

@Tomdango is this approach ok with you?

**Comment by Tomdango** [comment]
Happy with this approach, LGTM :+1:

**Comment by ClarkeCDC** [comment]
Thanks for the feedback both

**Pull request merged**
